language: csharp

mono:
  - latest
  - 4.2.2
  - 4.0.5

os:
  - osx

#  - linux  disabled for now because the standard packages don't come with F# PCL FSharp.Core.dll

sudo: false  # use the new container-based Travis infrastructure 

script: 
  - ./build.sh RunTests
