language: csharp
dist: trusty

mono:
  - weekly
  - latest
  - 5.8.0

dotnet: 2.1.100-preview-007363

matrix:
  include:
    - mono: 5.8.0
      dotnet: 2.1.100-preview-007363
    - mono: 5.8.0
      env: USE_MSBUILD=1
      dotnet: 2.1.100-preview-007363
    - mono: latest
      env: USE_MSBUILD=1
      dotnet: 2.1.100-preview-007363
    - mono: weekly
      env: USE_MSBUILD=1
      dotnet: 2.1.100-preview-007363

os:
  - linux
  - osx

sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh NuGet
