language: csharp
dist: trusty

mono:
  - weekly
  - nightly
  - beta
  - latest
  - 5.2.0


# 5.2.0 doesn't work because we like to use installed F# compiler which can produce netstandard 2.0 code
#  - 5.2.0

dotnet: 2.0.0

os:
  - linux

# Travis OSX is in trouble installing dotnet 2.0.0 at all
#  - osx

sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh RunTests
