language: csharp
dist: trusty

mono:
  - 5.8.0
  - latest
  - weeky

dotnet: 2.1.100-preview-007363

os:
  - linux
  - osx

# have to add dotnet to each mono build config because Travis doesn't have an 'include both runtimes' option
matrix:
  include:
    - mono: 5.8.0
      dotnet: 2.1.100-preview-007363
      os: linux
    - mono: 5.8.0
      dotnet: 2.1.100-preview-007363
      env: USE_MSBUILD=1
      os: linux
    - mono: latest
      dotnet: 2.1.100-preview-007363
      env: USE_MSBUILD=1
      os: linux
    - mono: weekly
      env: USE_MSBUILD=1
      dotnet: 2.1.100-preview-007363
      os: linux
    - mono: 5.8.0
      dotnet: 2.1.100-preview-007363
      os: osx
    - mono: 5.8.0
      env: USE_MSBUILD=1
      dotnet: 2.1.100-preview-007363
      os: osx

sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh NuGet
