language: csharp
dist: trusty

mono:
  - weekly
  - nightly
  - beta
  - latest
  - 5.2.0

# weekly, nightly, beta don't work because of msbuild package install problems
#  beta

# 5.4.0 doesn't work because of missing SDK build things for F# new styleprojects + msbuild
#  - latest

# 5.2.0 doesn't work because of missing SDK build things for F# new styleprojects + msbuild
#  - 5.2.0

dotnet: 2.0.0

os:
  - linux

# Travis OSX is in trouble installing dotnet 2.0.0 at all
#  - osx

sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh RunTests
